In [3]:
conda install numpy

Retrieving notices: ...working... done
Solving environment: ...working... done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [5]:
a = np.zeros((4,10))
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
b = np.eye(10)
b

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [10]:
c = np.empty((4,10))
c

array([[6.95310461e-310, 1.42601338e-311, 6.91691904e-323,
        6.95310461e-310, 2.12199579e-314, 6.95310461e-310,
        0.00000000e+000, 6.95310461e-310, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 4.24399158e-311, 2.12199579e-311,
        4.94065646e-321, 0.00000000e+000, 4.94065646e-324,
        0.00000000e+000, 1.42602407e-311, 1.42602426e-311,
        1.97626258e-323],
       [0.00000000e+000, 0.00000000e+000, 4.94065646e-324,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 7.41098469e-323, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 7.41098469e-323, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

# create a 3*3*3 array with random value 

In [12]:
#2
random_array = np.random.random((3,3,3))
print(random_array)

[[[0.90104987 0.83512215 0.83381885]
  [0.85660895 0.44317722 0.26704612]
  [0.74922097 0.01038028 0.57916256]]

 [[0.00110954 0.01881339 0.19033388]
  [0.46340337 0.89833455 0.53760843]
  [0.24737835 0.59962099 0.50506638]]

 [[0.78993875 0.78510325 0.41897106]
  [0.27445554 0.9738392  0.06626582]
  [0.83555257 0.02352594 0.90758405]]]


In [16]:
#3
diagonal_mat=np.zeros((5,5))

for i in range(1,5):
    diagonal_mat[i,i-1]=i


print(diagonal_mat)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [24]:
#4

# 5Create an 8x8 matrix
matrix = np.zeros((8, 8), dtype=int)

# Fill the checkerboard pattern with alternating 0s and 1s
matrix[1::2, ::2] = 1  # Odd rows, even columns
matrix[::2, 1::2] = 1  # Even rows, odd columns

print(matrix)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [28]:
random_mat = np.random.random((5,5))
random_mat

array([[0.6789325 , 0.24134644, 0.44694336, 0.50297045, 0.43627802],
       [0.39971369, 0.10035381, 0.25915444, 0.68638748, 0.57103016],
       [0.53452743, 0.70780916, 0.53062213, 0.648508  , 0.35419399],
       [0.00812397, 0.85602344, 0.93379766, 0.92973402, 0.54263525],
       [0.27181308, 0.03921516, 0.5649199 , 0.62354943, 0.05651228]])

In [31]:
#5 Sample arrays
array1 = [1, 7, 3, 4, 0]
array2 = [3, 4, 5, 6, 7]
array3 = [5, 6, 7, 8, 9]

# Find the common values using set intersection
common_values = set(array1).intersection(array2, array3)

print("Common values:", common_values)


Common values: {7}


In [38]:
#6
from datetime import datetime, timedelta

# Get today's date
today = datetime.now()

# Calculate yesterday and tomorrow
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

# Format the dates as strings
today_str = today.strftime('%Y-%m-%d')
yesterday_str = yesterday.strftime('%Y-%m-%d')
tomorrow_str = tomorrow.strftime('%Y-%m-%d')

print("Yesterday:", yesterday_str)
print("Today:", today_str)
print("Tomorrow:", tomorrow_str)


Yesterday: 2023-09-20
Today: 2023-09-21
Tomorrow: 2023-09-22


In [37]:
#7
array1 = [1, 2, 3, 4, 5]
array2 = [1, 2, 3, 4, 5]

if array1 == array2:
    print("The arrays are equal.")
else:
    print("The arrays are not equal.")


The arrays are equal.


In [43]:
#8 
random_vector = np.random.rand(10)

indices_to_replace = np.random.choice(10, 3, replace=False)  # Replace 3 random values
random_vector[indices_to_replace] = 0

print("Random vector with some values replaced by 0:")
print(random_vector)


Random vector with some values replaced by 0:
[0.6874815  0.01720451 0.31125043 0.         0.47945407 0.60595929
 0.18234666 0.56870861 0.         0.        ]


In [44]:
#9
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


for row in arr:
    for val in row:
        print(val)


1
2
3
4
5
6
7
8
9


In [ ]:
#10
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Calculate the mean of each row
row_means = np.mean(matrix, axis=1, keepdims=True)

# Subtract the mean of each row from the respective row
matrix_minus_mean = matrix - row_means

print("Original matrix:")
print(matrix)
print("Matrix after subtracting the mean of each row:")
print(matrix_minus_mean)

In [ ]:
#11

original_vector = np.array([10, 20, 30, 40, 50, 60])

# Sample index vector (indices to be incremented)
index_vector = np.array([1, 3, 2, 1])  

# Ensure unique indices and count occurrences
unique_indices, counts = np.unique(index_vector, return_counts=True)

# Add 1 to the unique indices based on their counts
original_vector[unique_indices] += counts

print("Original vector:", original_vector)


In [46]:
#12
import numpy as np

# Sample matrices
A = np.array([[16, 77], [53, 44]])
B = np.array([[54, 61], [79, 84]])

# Compute the product of the matrices
product_matrix = np.dot(A, B)

# Extract the diagonal elements of the product matrix
diagonal_product = np.diag(product_matrix)

print("Product matrix:")
print(product_matrix)
print("Diagonal of the product matrix:")
print(diagonal_product)


Product matrix:
[[6947 7444]
 [6338 6929]]
Diagonal of the product matrix:
[6947 6929]


In [48]:
#13

x = np.random.randint(0,10,50)

unique_values, counts = np.unique(x, return_counts=True)


most_frequent_index = np.argmax(counts)


most_frequent_value = unique_values[most_frequent_index]

print("Array:", x)
print("Most frequent value:", most_frequent_value)
print("Frequency:", counts[most_frequent_index])

Array: [1 1 9 3 4 7 7 9 5 4 8 2 6 5 5 8 9 7 8 8 1 4 6 6 4 0 6 6 1 7 1 3 0 8 1 8 3
 7 5 0 3 9 9 4 7 3 9 9 3 1]
Most frequent value: 1
Frequency: 7


In [49]:
#14

arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])

# Choose the value of n (number of largest values to retrieve)
n = 3

# Get the n largest values
n_largest_values = np.partition(arr, -n)[-n:]

print(f"The {n} largest values are: {n_largest_values}")


The 3 largest values are: [5 6 9]


In [50]:
#15 How to create a record array from a regular record

regular_record = np.array([(1, 'chota bheem', 25), (2, 'kaliya', 30)], dtype=[('id', int), ('name', 'U10'), ('age', int)])

record_array = np.rec.array(regular_record)

print("First record's id:", record_array.id)
print("First record's name:", record_array.name)
print("First record's age:", record_array.age)

First record's id: [1 2]
First record's name: ['chota bhee' 'kaliya']
First record's age: [25 30]


In [52]:
#16

arr = np.array([[19, 32, 12], [14, 15, 16], [17, 18, 19]])

row1_index = 0
row2_index = 1


temp_row = np.copy(arr[row1_index])
arr[row1_index] = arr[row2_index]
arr[row2_index] = temp_row

print("Array after swapping rows:")
print(arr)


Array after swapping rows:
[[14 15 16]
 [19 32 12]
 [17 18 19]]


In [60]:
#17

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Print the original array and its shape
print("Original array:")
print(original_array)
print("Original array shape:", original_array.shape)

# Reshape the array to a 1D array
reshaped_array = original_array.reshape(-1)  # -1 means the dimension is inferred
print("\nReshaped to 1D array:")
print(reshaped_array)
print("Reshaped array shape:", reshaped_array.shape)


Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Original array shape: (3, 3)

Reshaped to 1D array:
[1 2 3 4 5 6 7 8 9]
Reshaped array shape: (9,)


In [ ]:
np_olympic_country=np.array([ 'GBR', 'Chine', 'RUS', 'US', 'KOR', 'JPN', 'GER']) 
np_olympic_country_gold=np.array([29,38,24,46,13,7,11])
np_olympic_country_silver=np.array([17,28,25,28,8,14,11]) 
np_olympic_country_Bronze=np.array([19,22,32,29,7,17,14])

In [63]:
max_gold_index = np.argmax(np_olympic_country_gold)

# Print the country with the maximum gold and its index

print("Index of the country with the maximum gold:", max_gold_index)


Index of the country with the maximum gold: 3


In [64]:
print("Country with the maximum gold:", np_olympic_country[max_gold_index])

Country with the maximum gold: US


In [68]:
total_medals = np_olympic_country_gold + np_olympic_country_silver + np_olympic_country_Bronze

most_medals_country = np_olympic_country[np.argmax(total_medals)]

print("The country with the most medals is:", most_medals_country)

The country with the most medals is: US
