In [1]:
import pandas as pd 
import numpy as np
import nltk 
from nltk.util import ngrams
import re
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
# BOW 
data = pd.read_csv('abcnews-date-text.csv') 

headlines = data['headline_text']

dataset = []
for headline in headlines:
    headline = headline.lower()  # Convert to lowercase
    headline = re.sub(r'\W', ' ', headline)  # Remove non-word characters
    headline = re.sub(r'\s+', ' ', headline)  # Remove extra whitespaces
    tokens = nltk.word_tokenize(headline)  # Tokenize the headline
    dataset.append(' '.join(tokens))  # Append tokenized headline to the dataset

print(dataset[:5])  # Print the first 5 tokenized headlines for verification

['aba decides against community broadcasting licence', 'act fire witnesses must be aware of defamation', 'a g calls for infrastructure protection summit', 'air nz staff in aust strike for pay rise', 'air nz strike to affect australian travellers']


In [3]:
vectorizer = CountVectorizer()
bow_representation = vectorizer.fit_transform(dataset[:5])  # Use the processed headlines

bow_array = bow_representation.toarray()

print(bow_array)

[[1 0 0 1 0 0 0 0 0 1 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0]
 [0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 1 0 1 1 1 0 0 0 0]
 [0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0]]


In [4]:

#N-Grams
data = pd.read_csv('abcnews-date-text.csv')

headlines = data['headline_text']

dataset = []
for headline in headlines:
    headline = headline.lower()  # Convert to lowercase
    headline = re.sub(r'\W', ' ', headline)  # Remove non-word characters
    headline = re.sub(r'\s+', ' ', headline)  # Remove extra whitespaces
    tokens = nltk.word_tokenize(headline)  # Tokenize the headline
    dataset.append(tokens)  # Append tokenized headline to the dataset

n = 2  # Set the value of n for n-grams (bigrams in this case)
bigrams = list(ngrams(dataset[:5], n))  # Generate n-grams from the first 5 tokenized headlines

print(f"Original text: {dataset[:5]}")
print()
print(f"Generated {n}-grams:")
for gram in bigrams:
    print(gram)


Original text: [['aba', 'decides', 'against', 'community', 'broadcasting', 'licence'], ['act', 'fire', 'witnesses', 'must', 'be', 'aware', 'of', 'defamation'], ['a', 'g', 'calls', 'for', 'infrastructure', 'protection', 'summit'], ['air', 'nz', 'staff', 'in', 'aust', 'strike', 'for', 'pay', 'rise'], ['air', 'nz', 'strike', 'to', 'affect', 'australian', 'travellers']]

Generated 2-grams:
(['aba', 'decides', 'against', 'community', 'broadcasting', 'licence'], ['act', 'fire', 'witnesses', 'must', 'be', 'aware', 'of', 'defamation'])
(['act', 'fire', 'witnesses', 'must', 'be', 'aware', 'of', 'defamation'], ['a', 'g', 'calls', 'for', 'infrastructure', 'protection', 'summit'])
(['a', 'g', 'calls', 'for', 'infrastructure', 'protection', 'summit'], ['air', 'nz', 'staff', 'in', 'aust', 'strike', 'for', 'pay', 'rise'])
(['air', 'nz', 'staff', 'in', 'aust', 'strike', 'for', 'pay', 'rise'], ['air', 'nz', 'strike', 'to', 'affect', 'australian', 'travellers'])


In [5]:
from nltk.util import ngrams as nltk_ngrams

data = pd.read_csv('abcnews-date-text.csv')

headlines = data['headline_text']

dataset = []
for headline in headlines:
    headline = headline.lower()  # Convert to lowercase
    headline = re.sub(r'\W', ' ', headline)  # Remove non-word characters
    headline = re.sub(r'\s+', ' ', headline)  # Remove extra whitespaces
    tokens = nltk.word_tokenize(headline)  # Tokenize the headline
    dataset.append(tokens)  # Append tokenized headline to the dataset

n = 3  # Set the value of n for n-grams (trigrams in this case)
generated_ngrams = list(nltk_ngrams(dataset[:6], n))  # Generate n-grams from the first 6 tokenized headlines

print(f"Original text: {dataset[:6]}")
print()
print(f"Generated {n}-grams:")
for gram in generated_ngrams:
    print(gram)

Original text: [['aba', 'decides', 'against', 'community', 'broadcasting', 'licence'], ['act', 'fire', 'witnesses', 'must', 'be', 'aware', 'of', 'defamation'], ['a', 'g', 'calls', 'for', 'infrastructure', 'protection', 'summit'], ['air', 'nz', 'staff', 'in', 'aust', 'strike', 'for', 'pay', 'rise'], ['air', 'nz', 'strike', 'to', 'affect', 'australian', 'travellers'], ['ambitious', 'olsson', 'wins', 'triple', 'jump']]

Generated 3-grams:
(['aba', 'decides', 'against', 'community', 'broadcasting', 'licence'], ['act', 'fire', 'witnesses', 'must', 'be', 'aware', 'of', 'defamation'], ['a', 'g', 'calls', 'for', 'infrastructure', 'protection', 'summit'])
(['act', 'fire', 'witnesses', 'must', 'be', 'aware', 'of', 'defamation'], ['a', 'g', 'calls', 'for', 'infrastructure', 'protection', 'summit'], ['air', 'nz', 'staff', 'in', 'aust', 'strike', 'for', 'pay', 'rise'])
(['a', 'g', 'calls', 'for', 'infrastructure', 'protection', 'summit'], ['air', 'nz', 'staff', 'in', 'aust', 'strike', 'for', 'pay',

In [7]:
#TF-IDF

from sklearn.feature_extraction.text import TfidfVectorizer

data = pd.read_csv('abcnews-date-text.csv')

headlines = data['headline_text']

dataset = []
for headline in headlines:
    headline = headline.lower()  # Convert to lowercase
    headline = re.sub(r'\W', ' ', headline)  # Remove non-word characters
    headline = re.sub(r'\s+', ' ', headline)  # Remove extra whitespaces
    #tokens = nltk.word_tokenize(headline)  # Tokenize the headline
    dataset.append(headline)
    
tfidf = TfidfVectorizer()
x_tfidf = tfidf.fit_transform(dataset[:6])  # Use the preprocessed headlines

feature_names_tfidf = tfidf.get_feature_names_out()

print('Feature Names(TF-IDF):\n',feature_names_tfidf)

print()

print('TF-IDF Matrix:\n',x_tfidf.toarray())

Feature Names(TF-IDF):
 ['aba' 'act' 'affect' 'against' 'air' 'ambitious' 'aust' 'australian'
 'aware' 'be' 'broadcasting' 'calls' 'community' 'decides' 'defamation'
 'fire' 'for' 'in' 'infrastructure' 'jump' 'licence' 'must' 'nz' 'of'
 'olsson' 'pay' 'protection' 'rise' 'staff' 'strike' 'summit' 'to'
 'travellers' 'triple' 'wins' 'witnesses']

TF-IDF Matrix:
 [[0.40824829 0.         0.         0.40824829 0.         0.
  0.         0.         0.         0.         0.40824829 0.
  0.40824829 0.40824829 0.         0.         0.         0.
  0.         0.         0.40824829 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.35355339 0.         0.         0.         0.
  0.         0.         0.35355339 0.35355339 0.         0.
  0.         0.         0.35355339 0.35355339 0.         0.
  0.         0.         0.         0.35355339 0.         0.35355339
  0.         0.     

In [8]:
# One-Hot Encoding

from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
import re
import nltk

data = pd.read_csv('abcnews-date-text.csv')

headlines = data['headline_text']

processed_headlines = []
for headline in headlines:
    headline = headline.lower()  # Convert to lowercase
    headline = re.sub(r'\W', ' ', headline)  # Remove non-word characters
    headline = re.sub(r'\s+', ' ', headline)  # Remove extra whitespaces
    processed_headlines.append(headline)

# Using CountVectorizer for one-hot encoding
count_vectorizer = CountVectorizer(binary=True)
x_one_hot = count_vectorizer.fit_transform(processed_headlines[:6])  # Use the processed headlines

feature_names_one_hot = count_vectorizer.get_feature_names_out()

print('Feature Names (One-Hot Encoding):\n', feature_names_one_hot)
print()
print('One-Hot Encoded Matrix:\n', x_one_hot.toarray())


Feature Names (One-Hot Encoding):
 ['aba' 'act' 'affect' 'against' 'air' 'ambitious' 'aust' 'australian'
 'aware' 'be' 'broadcasting' 'calls' 'community' 'decides' 'defamation'
 'fire' 'for' 'in' 'infrastructure' 'jump' 'licence' 'must' 'nz' 'of'
 'olsson' 'pay' 'protection' 'rise' 'staff' 'strike' 'summit' 'to'
 'travellers' 'triple' 'wins' 'witnesses']

One-Hot Encoded Matrix:
 [[1 0 0 1 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 0 0 0]
 [0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 1 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0]]
